version: "3"

services:
    db:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=supersecret
            - MYSQL_DATABASE=go-auth-grpc-gateway
            - MYSQL_USER=user
            - MYSQL_PASSWORD=supersecret
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
    users:
        build:
            context: ./users
        image: marceloaguero/go-auth-grpc-gateway-users:local
        environment:
            - PORT=8080
            - DB_DSN=:supersecret@tcp(db:3306)
            - DB_NAME=go-auth-grpc-gateway
        ports:
            - "8080:8080"
        depends_on:
            - db
volumes:
    db-data:

